### ISSUE TITLE
Suggestion: Autosearch 

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#10]
testing v0.8

Can I suggest that the clipboard automatically filters after you type two or three characters? - this will speed up finding and selecting stuff.

**Comment by prateekmedia** [comment]
Yeah, but Gtk.Entry doesnt support something like that , it only have activate signal which is activated when you press enter.

If you know any other widget or other things related to code this then I can implement it.

**Comment by fossfreedom** [comment]
changed is an inherited signal which you can use - see https://github.com/UbuntuBudgie/budgie-extras/blob/master/budgie-weathershow/src/weathershow/WeatherShow.vala#L826  and the connected method later in the same module

**Comment by prateekmedia** [comment]
> changed is an inherited signal which you can use - see https://github.com/UbuntuBudgie/budgie-extras/blob/master/budgie-weathershow/src/weathershow/WeatherShow.vala#L826 and the connected method later in the same module

Thanks, will use that to search instead

**Comment by prateekmedia** [comment]
Thanks
