### ISSUE TITLE
Suggestion: Paste when choosing

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#11]
Testing v0.8

 Can I make a suggestion that in the applet settings there is an option to paste automatically when selecting a clipboard entry?

**Comment by prateekmedia** [comment]
Where to paste automatically, clicking on clipboard applet will lose its focus on active window,

Can you elaborate more..?

**Comment by prateekmedia** [comment]
Looks like it is possible but I coudn't find any sufficent resources to do neither in valadoc.org nor in gnome documentation

**Comment by Jacob-Vlijm** [comment]
I can help you out with that, but it has to be somewhere this weekend. Teaching all day today :)

**Comment by prateekmedia** [comment]
> I can help you out with that, but it has to be somewhere this weekend. Teaching all day today :)

Sure why not.  :)

**Comment by Jacob-Vlijm** [comment]
Waitwait, you don't need anything like that. Clicking an applet in the panel doesn't change the active window, so you can just pick the latest active (valid) window.

**Comment by prateekmedia** [comment]
> Waitwait, you don't need anything like that. Clicking an applet in the panel doesn't change the active window, so you can just pick the latest active (valid) window.

Yeah I also noticed that, but I dont know how to trigger paste event in vala
