### ISSUE TITLE
Suggestion: Tidy the interface

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#13]
Can I make a gentle suggestion - ignore if you don't want to go there.

In essence the applet is here to record & access clipboard entries - so the popup should just have a search field and the rest to be a scrollable list of clipboard entries.  That will simplify the immediate interface to what the end-user will be using the applet for.

Any options such as Edit Mode/Private Mode/Empty Clipboard/anything else won't be used that often - so it doesn't need to be in the initial popup.

I would suggest next to the edit field have a ">" or other icon for "options".  Clicking that will move the GtkStack to reveal the empty clipboard/edit mode/private mode/anything else in the future.  The user then clicks the "<" to move back to the main GtkStack view.

**Comment by prateekmedia** [comment]
Hmm I already have an option of minimal interface on Budgie desktop settings

I have tried to make it scroll able using ScrolledWindow but cant succeed completely,  maybe anything you can help here,
I cant set height and width of it that respects the screen size.

I should use the Gtk stack and yeah I liked the suggestion to have that by default

**Comment by fossfreedom** [comment]
So I would use a Gtk.Box within a GtkStack - pack_start (Gtk.ScrolledWindow, true, true) to ensure the scrolled window is expanded fully in the popup.  

Add the Gtk.Listbox into the scrolled window and make sure you set the overlay scrolling and policy https://github.com/UbuntuBudgie/budgie-extras/blob/fcd8dd775c2ae684959898561bd3a4f52c7f6795/budgie-app-launcher/src/budgie-app-launcher/AppLauncherApplet.py#L138

The size of the popup will then determine the number of rows displayed - so just have an average of 6 or so rows because you dont want a huge popup.

Set the size of the popup https://github.com/UbuntuBudgie/budgie-extras/blob/master/budgie-app-launcher/src/budgie-app-launcher/AppLauncherApplet.py#L105

**Comment by prateekmedia** [comment]
[x] ScrolledWindow
