### ISSUE TITLE
Suggestion: Order by last used

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#14]
Can I make a suggestion for a possible future enhancement - I see that the last used clip is in bold which is great.

I'm used to seeing the clipboard entries ordered by last used (most recent first) - so that your eyes are always guided to the first few entries.

So the listbox is ordered by date (most recent used).

**Comment by prateekmedia** [comment]
Do you mean when you click on a clip then put it at top , or put selected clip at top?

**Comment by fossfreedom** [comment]
When you select and use a clip it moves to the top. So the most recently
clicked on always at the top, down to the least/last used

**Comment by prateekmedia** [comment]
Please let me know your thoughts on new update
