### ISSUE TITLE
assertion errors when clicking on any clips

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#15]
Testin v0.8.9

![image](https://user-images.githubusercontent.com/996240/101193855-12c5b900-3655-11eb-9a47-f00183200001.png)

When clicking on any clips - I see lots of assertion errors as per the picture

**Comment by prateekmedia** [comment]
I would be happy to solve this but I am not aware what could be causing this

**Comment by prateekmedia** [comment]
Please test it out and If it remains then let me know
