### ISSUE TITLE
Assertion error when deleting search for text

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#17]
![image](https://user-images.githubusercontent.com/996240/101241459-10636d80-36ee-11eb-820d-1f0f5a8c0bbd.png)

Testing v0.9

So I searched for some text - the list filtered ok.  I then hit backspace until the search field was empty when I noticed the assertion message in the picture

**Comment by prateekmedia** [comment]
Lemme see

**Comment by prateekmedia** [comment]
I cannot reproduce the error, still will look into it
