### ISSUE TITLE
string_strip messages when copying images

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#18]
![image](https://user-images.githubusercontent.com/996240/101241615-90d69e00-36ef-11eb-9ee4-f79b75eeba5c.png)

Testing v0.9

So in my setup I've got a QEMU 21.10 Ubuntu Budgie with the clipboard applet running.

On my host which happens to be 20.04 Ubuntu Budgie I have the budgie screenshot applet

I was taking a screenshot - I noticed when I was using the screenshot applet to copy the image in the virtual machine with the clipboard applet I saw two string_strip messages.

In addition I can see extra rows  in the list box which I'm guessing is the attempt to copy the image (?) but as text (maybe)?

**Comment by prateekmedia** [comment]
I dont know, I have not implemented the feature yet.

Question : Do you have enabled anything extra using Budgie desktop settings of clipboard applet? Get selection on clipboard?

**Comment by prateekmedia** [comment]
I cannot reproduce the same error :( can you try the same on you 20.04  host machine or in any virtual box type thing.


I will try to remove some checks like `text !=null` where necessary in trying to fix this and #17

**Comment by fossfreedom** [comment]
Try inkscape - just draw  a square in inkscape and copy immediately via
CTRL + C

**Comment by prateekmedia** [comment]
Ok lemme try and if it happens then I would remove extra unwanted checks
and other things which are causing this

**Comment by prateekmedia** [comment]
Fixed it but now a new warning is coming in terminal which is a minor one so it doesn't matter, I tried to reproduce it using Inkscape and my budgie-panel crashed everytime due to this, but now its just fine,

New error / warning, maybe its related to inkscape..?
```
SPDocument::doUnref(): invalid ref count! -1
```

and please don't open a new issue with this error as I don't know its solution till I fix #2
