### ISSUE TITLE
Don't save history via schemas

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#21]
I note the intention is to save clips to the gsettings schema.  Can I kindly suggest that this practically will not work.

For instance - you could copy megabytes of text from - say - a libreoffice document.  This wouldn't go into the gsettings schema - there is a limit - I forget how big - but its certainly not megabytes.

Also - if the future intention is to support images then images won't go into the schema - a file/database format will be better from a future expandability point-of-view

Suggestion is that manage the clips via a .config/budgie-clipboard-applet local folder - either via file based or some-sort of mini SQL type lightweight database.

**Comment by prateekmedia** [comment]
@fossfreedom Ok hmm, Let's see then, how do you store quicknote applets data by the way?

**Comment by fossfreedom** [comment]
Its via a file https://github.com/UbuntuBudgie/budgie-extras/blob/master/budgie-quicknote/QuickNoteApplet.vala#L85

https://github.com/UbuntuBudgie/budgie-extras/blob/master/budgie-quicknote/QuickNoteApplet.vala#L255

**Comment by prateekmedia** [comment]
> Its via a file https://github.com/UbuntuBudgie/budgie-extras/blob/master/budgie-quicknot....

Ok Thanks :)
