### ISSUE TITLE
blank line always added on panel restart

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#23]
**Describe the bug**
A blank row is always inserted at the top of the list of clips on restart of the panel

**To Reproduce**

    killall budgie-panel
    rm -rf ~/.config/prateekmedia
    budgie-panel --replace &

Delete the blank line and restart the panel again - note the new blank row again.

**Expected behavior**
not a blank line

**Screenshots**

![image](https://user-images.githubusercontent.com/996240/102391193-45fd3600-3fcd-11eb-8e33-d4792d48fef2.png)

**Desktop (please complete the following information):**
 - Distro: UB 20.10
 - Applet Version 0.9.9

**Additional context**
N/A

**Comment by prateekmedia** [comment]
Next time please send a pull requests as I am AFK due to exams.
