### ISSUE TITLE
assertion errors in the terminal

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#6]
Trying v0.8 as per the README - Note - is this an official version because I don't see a release/tag for v0.8

![image](https://user-images.githubusercontent.com/996240/101079124-f6ffdb80-359e-11eb-8de8-ada5927c31c7.png)

Clicking the empty label - that's a little strange to be able to click.  But anyway - doing so you see lots of assertion failed messages in the terminal

**Comment by prateekmedia** [comment]
It's in beta as some features are to be implemented, also how do I make it a release , will the release include source code or something like deb package or eopkg package?

Looks like I missed some code , Thanks will see this

**Comment by fossfreedom** [comment]
Git releases are just source tarballs.  You can attach additional files if you want to a release such as .eopkg, .deb but you have to create these yourself or via a github action.

I have prepared a .deb package for Ubuntu Budgie  and will make it available when you are happy and git tagged a stable release.

**Comment by prateekmedia** [comment]
Thanks, Closing this for now
