### ISSUE TITLE
debug output when copying

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#7]
Testing v0.8

![image](https://user-images.githubusercontent.com/996240/101079438-64137100-359f-11eb-9ea3-1580130098e0.png)

Whenever you copy any text you see what appears to be debug messages in the terminal which as a little unexpected.

**Comment by prateekmedia** [comment]
It was only in 0.8 will remove it in future version, I wanted to test out private and edit mode and other things that's why I kept it

**Comment by prateekmedia** [comment]
Fixed in d3a015b9e651fbbc822c9f3013cf0aab31d34b98
