### ISSUE TITLE
Suggestion: Use tooltips

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#8]
Looking at v0.8

I saw two switches - edit mode and private mode.

I don't know what they are supposed to-do - its not really obvious - maybe add a tooltip for these to describe what they do?

**Comment by prateekmedia** [comment]
Ok will add tooltio to Gtk.Label, 
and edit mode basically adds X / Cancel button after every clipboard entry and private mode doesnt records your clipboard when enabled

**Comment by prateekmedia** [comment]
Fixed in d3a015b9e651fbbc822c9f3013cf0aab31d34b98
