### ISSUE TITLE
Clickable blank rows

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-clipboard-applet#9]
testing v0.8

![image](https://user-images.githubusercontent.com/996240/101079940-0d5a6700-35a0-11eb-8d0a-de4f912dbb4b.png)

There appears to me lots of blank rows you can click onto under the 3/10 in the picture which was a little unexpected.

**Comment by prateekmedia** [comment]
Ok lemme se that

**Comment by prateekmedia** [comment]
Fixed in 14d107345632c13c011cee079e489b2363209d60
